Assignment_01 Submission
shailbala/DSVV-MCA25-TestProject pull request #21
Opened 2024-03-16 12:46 UTC by TechieTripathi

2024-03-18 00:23 UTC, shailbala commented on Assignment_01/Vishnu Tripathi/templates/userGenerator.html
> +        function generateUsername() {
Can you create this function in the python script?

2024-03-18 00:35 UTC, shailbala requested changes

2024-03-18 00:35 UTC, shailbala commented on Assignment_01/Vishnu Tripathi/templates/home.html
> +    <form action="/data" method="POST" id="form">
Instead of directing to `/data` from here, can you check in the the `form()` function if its a POST request, read the values given by user, then direct it to `/data` using `redirect` or `url_for`?

2024-03-18 00:35 UTC, shailbala commented on Assignment_01/Vishnu Tripathi/app.py
> +from flask import Flask, render_template, request,  redirect, url_for
You have imported `redirect` and `url_for` but have not used it anywhere

2024-03-18 00:35 UTC, shailbala commented
Do not close this Pull Request, add new commits, making the required changes and let me know.

2024-03-21 16:13 UTC, TechieTripathi commented on Assignment_01/Vishnu Tripathi/templates/userGenerator.html
> +        function generateUsername() {
Okie Mam

2024-03-21 17:02 UTC, TechieTripathi commented on Assignment_01/Vishnu Tripathi/templates/home.html
> +    <form action="/data" method="POST" id="form">
Done

2024-03-21 17:04 UTC, TechieTripathi commented on Assignment_01/Vishnu Tripathi/app.py
> +from flask import Flask, render_template, request,  redirect, url_for
I didn't create this from scratch I just reused some of my previous code.

2024-03-21 17:06 UTC, TechieTripathi commented
Yes mam, I made all the changes according to your guidance.

2024-04-08 06:45 UTC, merged